# Generated by Django 3.1.7 on 2021-09-13 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210911_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=150)),
                ('website_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
