# Generated by Django 3.1.7 on 2021-09-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210913_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='platform',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.streamingplatforms'),
        ),
    ]
