# Generated by Django 3.1.7 on 2021-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20210921_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='avg_review',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='no_of_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
